### Importing Useful Libraries

In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By

In [2]:
import urllib3
from requests.packages.urllib3.exceptions import InsecureRequestWarning

# Suppress InsecureRequestWarning
urllib3.disable_warnings(InsecureRequestWarning)



In [3]:
training_data = pd.read_csv('./datasets/Training.csv')
testing_data = pd.read_csv('./datasets/Testing.csv')
training_data = training_data[training_data.columns[:-1]]
all_symptoms = training_data.columns
final_symptoms  = []
for i in all_symptoms:
    final_symptoms.append(i.replace('_', ' '))
training_data.columns = final_symptoms
testing_data.columns = final_symptoms
final_symptoms = final_symptoms[:-1]
output_file = open('all_symptoms.txt', 'w')

for symptom in final_symptoms:
    output_file.write('"' + symptom + '", ')

output_file.close()

Naive Bayes Classifier

In [4]:
# Split the dataset into features (X) and target (y)
X_train = training_data.iloc[:, :132]  # Features
y_train = training_data.iloc[:, -1]   # Target
X_test = testing_data.iloc[:, :132]  # Features
y_test = testing_data.iloc[:, -1]   # Target
# print(X_test)
# Create and train the Naive Bayes classifier
naive_bayes_classifier = MultinomialNB()
naive_bayes_classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred_nb = naive_bayes_classifier.predict(X_test)

# Evaluate the classifier
accuracy = accuracy_score(y_test, y_pred_nb)
confusion = confusion_matrix(y_test, y_pred_nb)
classification_rep = classification_report(y_test, y_pred_nb)

print(f"Accuracy: {accuracy}")
print("Confusion Matrix:\n", confusion)
print("Classification Report:\n", classification_rep)

Accuracy: 1.0
Confusion Matrix:
 [[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
Classification Report:
                                          precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00         1
                                   AIDS       1.00      1.00      1.00         1
                                   Acne       1.00      1.00      1.00         1
                    Alcoholic hepatitis       1.00      1.00      1.00         1
                                Allergy       1.00      1.00      1.00         1
                              Arthritis       1.00      1.00      1.00         1
                       Bronchial Asthma       1.00      1.00      1.00         1
                   Cervical spondylosis       1.00      1.00      1.00         1
                            Chicken pox       1.00      1.00      1.00         1
            

Using Decision Tree

In [5]:
# Create and train the Decision Tree classifier
decision_tree_classifier = DecisionTreeClassifier(random_state=42)
decision_tree_classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred_dt = decision_tree_classifier.predict(X_test)

# Evaluate the classifier
accuracy = accuracy_score(y_test, y_pred_dt)
confusion = confusion_matrix(y_test, y_pred_dt)
classification_rep = classification_report(y_test, y_pred_dt)

print(f"Accuracy: {accuracy}")
print("Confusion Matrix:\n", confusion)
print("Classification Report:\n", classification_rep)

Accuracy: 0.9761904761904762
Confusion Matrix:
 [[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
Classification Report:
                                          precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00         1
                                   AIDS       1.00      1.00      1.00         1
                                   Acne       1.00      1.00      1.00         1
                    Alcoholic hepatitis       1.00      1.00      1.00         1
                                Allergy       1.00      1.00      1.00         1
                              Arthritis       1.00      1.00      1.00         1
                       Bronchial Asthma       1.00      1.00      1.00         1
                   Cervical spondylosis       1.00      1.00      1.00         1
                            Chicken pox       1.00      1.00      1.00        

Using Random Forest

In [6]:
# Create and train the Random Forest classifier
random_forest_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
random_forest_classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred_rf = random_forest_classifier.predict(X_test)

# Evaluate the classifier
accuracy = accuracy_score(y_test, y_pred_rf)
confusion = confusion_matrix(y_test, y_pred_rf)
classification_rep = classification_report(y_test, y_pred_rf)

print(f"Accuracy: {accuracy}")
print("Confusion Matrix:\n", confusion)
print("Classification Report:\n", classification_rep)

Accuracy: 0.9761904761904762
Confusion Matrix:
 [[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
Classification Report:
                                          precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00         1
                                   AIDS       1.00      1.00      1.00         1
                                   Acne       1.00      1.00      1.00         1
                    Alcoholic hepatitis       1.00      1.00      1.00         1
                                Allergy       1.00      1.00      1.00         1
                              Arthritis       1.00      1.00      1.00         1
                       Bronchial Asthma       1.00      1.00      1.00         1
                   Cervical spondylosis       1.00      1.00      1.00         1
                            Chicken pox       1.00      1.00      1.00        

Using Gradient Boosting

In [ ]:
user_input=[0]*132
symptoms = []
#symptoms should fetch from JAVASCRIPT
for sym in symptoms:
    ind = final_symptoms.index(sym)
    user_input[ind] = 1
user_input = np.array(user_input).reshape(1,-1)
disease_nb = naive_bayes_classifier.predict(user_input)
disease_dt = decision_tree_classifier.predict(user_input)
disease_rf = random_forest_classifier.predict(user_input)

print(disease_nb, disease_dt, disease_rf)



In [8]:
import requests
from bs4 import BeautifulSoup

disease = "gerd"
url = f'https://www.diseaseinfosearch.org/search?term={disease}'

# Sending a GET request to the URL
response = requests.get(url, verify=False)

# Parsing the HTML content using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Finding the element with class 'details description'
description_element = soup.find(class_='details description')

if description_element:
    # Extracting the inner HTML content
    description_inner_html = description_element.decode_contents()

    # Printing or using the extracted content
    print(description_inner_html)
else:
    print("Element with class 'details description' not found.")

# Finding the element with class 'secondary-link double-arrow-right'
link_element = soup.find(class_='secondary-link double-arrow-right')

if link_element:
    # Extracting the URL from the 'href' attribute
    link_url = link_element.get('href')

    # Printing or using the extracted URL
    print("Link URL:", link_url)
else:
    print("Element with class 'secondary-link double-arrow-right' not found.")



                 Gastroesophageal reflux disease, or GERD, is caused by frequent acid reflux, which irritates the lining of the esophagus. GERD is generally diagnosed when a person experiences acid reflux more than two times per week. Acid reflux is a common condition in which stomach acid flows up into the esophagus. This causes a burning, painful feeling in the chest more ...            
Link URL: /GERD/9994


In [10]:
import requests
from bs4 import BeautifulSoup

# Step 1: Extract the link with class "secondary-link double-arrow-right"
search_url = 'https://www.diseaseinfosearch.org/search?term=GERD'
response = requests.get(search_url, verify=False)
soup = BeautifulSoup(response.content, 'html.parser')
# Find the element with the specified class
link_element = soup.find(class_='secondary-link double-arrow-right')

if link_element:
    # Extract the URL from the 'href' attribute
    extracted_link = link_element.get('href')

    # Step 2: Use the extracted link to fetch the content
    full_url = f'https://www.diseaseinfosearch.org{extracted_link}'
    content_response = requests.get(full_url, verify=False)
    content_soup = BeautifulSoup(content_response.content, 'html.parser')

    # Find all elements with the class 'content' and select the second one
    content_elements = content_soup.find_all(class_='content')

    # Ensure there are at least two 'content' class elements found
    if len(content_elements) >= 2:
        # Extract the second 'content' class element
        second_content_element = content_elements[1]

        # Extract inner HTML content of the second 'content' class element
        content_html = second_content_element.encode_contents().decode('utf-8')

        # Printing or using the extracted HTML content
        print(content_html)
    else:
        print("Second element with class 'content' not found in the extracted link.")
else:
    print("Element with class 'secondary-link double-arrow-right' not found in the search URL.")



<p><strong>Gastroesophageal reflux disease</strong>, or GERD, is caused by frequent acid reflux, which irritates the lining of the esophagus. GERD is generally diagnosed when a person experiences acid reflux more than two times per week.</p> <p>Acid reflux is a common condition in which stomach acid flows up into the esophagus. This causes a burning, painful feeling in the chest more commonly known as heartburn or acid indigestion. Your stomach makes a strong acid to help break down food and to protect you from bacteria. The stomach is not harmed by the acid because it has a special lining. The esophagus is the tube that takes your food from your mouth to your stomach. It does not have the special lining, so it will be irritated by the stomach acid. Normally a special ring of muscle, the lower esophageal sphincter (LES), keeps the stomach’s contents from flowing up into the esophagus. Acid reflux happens most often when the LES is not working correctly.</p> <p>Symptoms of acid reflux 

In [11]:
# Path to your ChromeDriver executable
chrome_driver_path = './chromedriver.exe'
medicine_html = ""
# Create a WebDriver instance
service = Service(chrome_driver_path)
driver = webdriver.Chrome(service=service)

url = "https://search.medscape.com/search/?q=%22gerd%22&plr=ref&contenttype=Drugs+%26+Neutraceuticals&page=1"

try:
    # Open the URL in the browser
    driver.get(url)

    # Find the divs with class "searchResult"
    div_responsive_tables = driver.find_elements(By.CLASS_NAME, "searchResult")

    if div_responsive_tables:
        # Extract the HTML content of the first 5 divs
        for index, div_responsive_table in enumerate(div_responsive_tables[:5]):
            div_html_content = div_responsive_table.get_attribute('outerHTML')
            medicine_html += div_html_content
            print(f"HTML content of div {index + 1} with class='searchResult':")
            print(div_html_content)
    else:
        print("Divs with class='searchResult' not found")

except Exception as e:
    print("An error occurred:", e)

finally:
    # Close the browser
    driver.quit()


HTML content of div 1 with class='searchResult':
<div class="searchResult"><p class="searchResultTitle"><a href="//reference.medscape.com/drug/nexium-nexium-24hr-esomeprazole-341998" onclick="wmdTrack('sr-msr_1',this)">esomeprazole</a></p><ul class="searchResultSubLinks"><li><a href="//reference.medscape.com/drug/nexium-nexium-24hr-esomeprazole-341998#3" onclick="wmdTrack(&quot;sr-msr_s1&quot;)">Interactions</a></li><li><a href="//reference.medscape.com/drug/nexium-nexium-24hr-esomeprazole-341998#4" onclick="wmdTrack(&quot;sr-msr_s2&quot;)">Adverse Effects</a></li><li><a href="//reference.medscape.com/drug/nexium-nexium-24hr-esomeprazole-341998#0" onclick="wmdTrack(&quot;sr-msr_s3&quot;)">Dosing &amp; Uses</a></li><li><a href="//reference.medscape.com/drug/nexium-nexium-24hr-esomeprazole-341998#5" onclick="wmdTrack(&quot;sr-msr_s4&quot;)">Warnings</a></li><li><a href="//reference.medscape.com/drug/nexium-nexium-24hr-esomeprazole-341998#10" onclick="wmdTrack(&quot;sr-msr_s5&quot;)">Phar